<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <!-- Írj egy olyan async függvényt, ami paraméterként promiseokat (akármennyi lehet, számuk nem ismert)
    kap. A visszatérési érték egy Promise legyen, abban az esetben, ha mindegyik Promise fullfilled lett,
    egyébként egy Error object, az üzenet pedig: “Promise Error in functionName”.
    A functionName a függvény neve. -->

    <script>

        let proA = new Promise((res, rej) => {
            setTimeout(() => {
                res("First Success");
            }, 1000);
        });

        let proB = new Promise((res, rej) => {
            setTimeout(() => {
                res("Second Error");
            }, 2000);
        });

        let proC = new Promise((res, rej) => {
            setTimeout(() => {
                rej("Third Error");
            }, 3000);
        });

        async function checkPromises(...promises) {
            const result = await Promise.allSettled(promises);
            let fulfilled = [];
            let rejected = [];
            for (let i=0; i<result.length; i++) {
                if (result[i].status === 'fulfilled') {
                    fulfilled.push(result[i].status);
                }
                if (result[i].status === 'rejected') {
                    rejected.push(i+1);
                }
            }
            if (fulfilled.length === promises.length) {
                return 'All promises were fulfilled';
            } else {
                return new Error (`Promise error in the following promise(s): ${rejected}`);
            }
            
        }

        checkPromises(proA, proB, proC).then(console.log);


    </script>

</body>

</html>